#!/bin/sh

set -e
set -x

if [ -z $WORKSPACE ]; then
    WORKSPACE=`pwd`
fi

./autogen.sh
# test ./configure
./configure
# now run the build
./configure --with-fuse
make clean
make -j4
ls -1 *.c *.h tests/c*.c | sort | \
    cppcheck --enable=all --file-list=- --max-configs=50 -I/usr/include --xml \
    2> cppcheck-result.xml
make check V=1
