/* Text to put at the beginning of the generated file. Probably a license. */

#ifndef libsqlfs_rs_h
#define libsqlfs_rs_h

#pragma once

/* Generated with cbindgen:0.16.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "sqlite3.h"
#include "fuse.h"

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

int readdir(void *Handle, const char *PathPtr, void *FillerBuff, fuse_fill_dir_t Filler);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* libsqlfs_rs_h */

/* Text to put at the end of the generated file */
